Add more helpful error message when file decoding fails
We've been running into an issue recently, specifically with Windows
users wherein ASCII content is being copied to and saved in a UTF-8
file. During parsing this causes a cryptic error message

```
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2907500: character maps to `<undefined>`
```

to occur during reading of the model config files. Assuming / guessing
the content of the file (and ignoring unknown characters) seems
dangerous as this has potential to make parts of the config invalid
during validation and thus becoming even harder to debug. Additionally,
files could potentially contain mixed encoded content. Thus the safest
thing to do seems to be explain what is happening and offer possible
remediations.